// Generated by backend/tools/export_contract.py; response defaults are always serialized.
export type MajorCategory = "medical" | "shopping" | "education" | "care" | "dining" | "finance" | "public" | "leisure" | "transport" | "life";
export type MinorCategory = "pharmacy" | "hospital_pharmacy" | "hospital" | "clinic" | "checkup" | "market" | "fresh_store" | "supermarket" | "school" | "combined_school" | "middle_school" | "college" | "preschool" | "training" | "nursing_home" | "rehab" | "restaurant" | "cafe" | "bank" | "finance_service" | "government" | "post" | "library" | "park" | "sports" | "entertainment" | "bus" | "parking" | "fuel" | "repair" | "beauty";
export type DisplayGroup = "healthcare" | "education" | "daily_life" | "public_mobility" | "leisure";
export type CheckupFacilities = {
  categories?: Array<MajorCategory>;
  maxPoiRequests?: number;
  maxRouteRequests?: number;
};

export type CheckupIsochrone = {
  budget?: number | null;
};

export type Origin = {
  lng: number;
  lat: number;
};

export type CheckupRequest = {
  schemaVersion?: "checkup-v1";
  clientRequestId: string;
  engine: string;
  center: Origin;
  coordinateSystem?: "bd09ll";
  isochrone?: CheckupIsochrone;
  facilities?: CheckupFacilities;
};

export type RetentionView = {
  detailsAvailable: boolean;
  expiresAt: number | null;
  reason: "session_closed" | "superseded" | "legacy" | "cleared" | null;
  sources: Array<string>;
  cleared: boolean;
};

export type TaskProgress = {
  step: string;
  label: string;
  count: number | null;
  limit: number | null;
  unit: string | null;
  since: number;
};

export type CheckupTaskView = {
  taskId: string;
  clientRequestId: string;
  engine: string;
  status: "queued" | "running" | "cancelling" | "completed" | "failed" | "cancelled";
  businessStatus: "complete" | "partial" | "insufficient" | null;
  stage: "isochrone" | "poi" | "accessibility" | "verification" | "reporting" | "ready" | null;
  revision: number;
  budget: number;
  requests: number;
  networkRequests: number;
  elapsedSeconds: number;
  createdAt: number;
  cancelRequested: boolean;
  error: string | null;
  serverTime: number;
  startedAt: number | null;
  finishedAt: number | null;
  stageStartedAt: number | null;
  lastActivityAt: number | null;
  progress: TaskProgress | null;
  retention: RetentionView | null;
};

export type AccessibilityEvidence = {
  status: "complete" | "partial" | "failed";
  domain: Record<string, unknown> | null;
  domainAreaM2: number | null;
  excludedAreaM2: number | null;
  gridStepM: number;
  refinedStepM: number;
  maxLeafCells: number;
  searchCutoffM: number;
  views: Record<string, unknown>;
  categories: Array<CategoryCoverage>;
  notes: Array<string>;
};

export type CategoryCoverage = {
  category: string;
  supported: boolean;
  coveredM2: number;
  gapM2: number;
  unknownM2: number;
  domainAreaM2: number | null;
  unavailableReason: string | null;
  cells: Record<string, unknown>;
  entrances: Record<string, unknown>;
  coverage: Record<string, unknown> | null;
};

export type CoverageRow = {
  category: string;
  supported: boolean | null;
  coverageLowerPct: number | null;
  coverageUpperPct: number | null;
  assessablePct: number | null;
  unknownPct: number | null;
  intervalWidthPct: number | null;
  intervalDegenerate: boolean | null;
  unavailableReason: string | null;
  coveredM2: number | null;
  gapM2: number | null;
  unknownM2: number | null;
  cells: Record<string, unknown>;
  entrances: Record<string, unknown>;
  evidenceGrade: string;
};

export type DistanceRule = {
  metric: "unconfirmed" | "straight_line" | "walking_route";
  threshold_m: number;
  inclusive: boolean | null;
  tolerance_m: number | null;
  assessment_scope: "unconfirmed" | "isochrone" | "community" | "sample";
  category_policy: "unconfirmed" | "per_category" | "major_minor";
};

export type EngineRef = {
  engineId: string;
  engineVersion: string;
  label: string;
};

export type FacilityGroup = {
  queryStatus: "completed" | "partial" | "failed" | "cancelled";
  catalogCompleteness: "unverified";
  provider: string;
  apiVersion: string;
  dataSource: "baidu_place" | "synthetic";
  queryDomain: Record<string, unknown>;
  dataObtainedAt: number | null;
  initialPlan: Record<string, unknown> | null;
  countsByCategory: Record<string, number>;
  facilities: Array<Record<string, unknown>>;
  nearbyFacilities: Array<Record<string, unknown>>;
  reviewCandidates: Array<Record<string, unknown>>;
  excludedCandidates: Array<Record<string, unknown>>;
  quarantine: Array<Record<string, unknown>>;
  queryCoverage: Array<Record<string, unknown>>;
  queryIncompleteRegions: Record<string, Array<Record<string, unknown>>> | null;
  queryAreaCoverage: Record<string, unknown> | null;
  sourceTasks: Record<string, Record<string, unknown>> | null;
  statistics: Record<string, unknown>;
  warnings: Array<string>;
  stopReason: string | null;
};

export type HeatmapEvidence = {
  metric: "walking_route";
  estimated: true;
  stepM: number;
  domain: Record<string, unknown> | null;
  categories: Record<string, Array<Record<string, unknown>>>;
  notes: Array<string>;
};

export type Issue = {
  code: string;
  message: string;
  scope: string;
  severity: "warning" | "error" | "pending";
};

export type OverallScore = {
  available: boolean;
  reason: string | null;
  missingCategories: Array<string>;
  coverageLowerPct: number | null;
  coverageUpperPct: number | null;
  assessablePct: number | null;
  unknownPct: number | null;
  categories: Array<string>;
  weights: Record<string, number>;
};

export type ReportEvidence = {
  reportId: string;
  generatedAt: number;
  schemaVersion: "checkup-v1";
  domain: Record<string, unknown> | null;
  domainAreaM2: number | null;
  categories: Array<CoverageRow>;
  overall: OverallScore | null;
  gaps: ReportGaps;
  verification: ReportVerification;
  evidence: ReportQuality;
  dataSources: Record<string, unknown> | null;
  limitations: Array<string>;
};

export type ReportGaps = {
  status: "complete" | "partial" | "failed";
  reason: string | null;
  zones: Array<ServiceZone>;
  byCategoryM2: Record<string, number>;
  compositeAreaM2: number;
  gapAreaM2: number;
  minLabelAreaM2: number;
  compositeMinCategories: number;
  obstacleLayerAvailable: boolean;
  notes: Array<string>;
};

export type ReportQuality = {
  schemaVersion: string;
  ruleVersion: string;
  sourceResultHash: string;
  views: Record<string, unknown> | null;
  grid: Record<string, unknown>;
  excludedAreaM2: number | null;
  obstacleLayerAvailable: boolean | null;
  heatmapEstimated: boolean | null;
  catalogCompleteness: string;
  queryStatus: string | null;
  notes: Array<string>;
};

export type ReportVerification = {
  available: boolean;
  status: string;
  provider: string | null;
  checked: number;
  failed: number;
  unresolved: number;
  facilities: Array<Record<string, unknown>>;
  conflicts: Array<Record<string, unknown>>;
  spotChecks: Array<Record<string, unknown>>;
  spotCheckSummary: Record<string, unknown>;
  localOverrides: Array<Record<string, unknown>>;
  queries: Record<string, unknown>;
  reason: string | null;
  notes: Array<string>;
};

export type ScopeEvidence = {
  projection: string;
  dataVersion: string;
  coverageSupported: boolean;
  assessmentDomainAvailable: boolean;
  excludedAreaM2: number | null;
  modelSupportAvailable: boolean;
  notes: Array<string>;
};

export type ScoreEvidence = {
  ruleVersion: string;
  domainAreaM2: number | null;
  categories: Array<ScoreRow>;
  overall: OverallScore | null;
  formula: Record<string, unknown>;
};

export type ScoreRow = {
  category: string;
  supported: boolean | null;
  coverageLowerPct: number | null;
  coverageUpperPct: number | null;
  assessablePct: number | null;
  unknownPct: number | null;
  intervalWidthPct: number | null;
  intervalDegenerate: boolean | null;
  unavailableReason: string | null;
};

export type ServiceGapsEvidence = {
  status: "complete" | "partial" | "failed";
  zones: Array<ServiceZone>;
  byCategoryM2: Record<string, number>;
  compositeAreaM2: number;
  gapAreaM2: number;
  compositeMinCategories: number;
  minLabelAreaM2: number;
  obstacleLayerAvailable: boolean;
  notes: Array<string>;
};

export type ServiceZone = {
  id: string;
  index: number;
  categories: Array<string>;
  kind: string;
  areaM2: number;
  parts: number;
  cellIds: Array<string>;
  labelVisible: boolean;
  suspected: boolean;
  evidenceGrade: string;
  queryStatus: string;
  nearestFacility: string | null;
  reason: string | null;
  suggestion: string;
  geometry: Record<string, unknown> | null;
  geometrySystem: "metric";
  displayGeometry: Record<string, unknown> | null;
};

export type TraceEvidence = {
  dataVersions: Record<string, unknown>;
  ruleVersions: Record<string, unknown>;
  isochroneHash: string;
  resultHash: string;
  budgets: Record<string, unknown>;
  recomputed: Record<string, unknown> | null;
  retried: Record<string, unknown> | null;
};

export type VerificationEvidence = {
  status: "complete" | "partial" | "failed" | "not_integrated";
  provider: string | null;
  checked: number;
  failed: number;
  unresolved: number;
  facilities: Array<Record<string, unknown>>;
  conflicts: Array<Record<string, unknown>>;
  spotChecks: Array<Record<string, unknown>>;
  spotCheckSummary: Record<string, unknown>;
  localOverrides: Array<Record<string, unknown>>;
  queries: Record<string, unknown>;
  reason: string | null;
  notes: Array<string>;
};

export type WaterDataEvidence = {
  obstacleLayerAvailable: boolean;
  osmDataVersion: string | null;
  sourcePbfSha256: string | null;
  reviews: Array<Record<string, unknown>>;
  rejectedReviews: Array<string>;
  domainAreaM2: number | null;
  reviewedAreaM2: number;
  unreviewedAreaM2: number | null;
  conflictAreaM2: number;
  statements: Array<string>;
};

export type CheckupSnapshot = {
  schemaVersion: "checkup-v1";
  taskId: string;
  revision: number;
  generatedAt: number;
  center: Origin;
  coordinateSystem: "bd09ll";
  stage: "isochrone" | "poi" | "accessibility" | "verification" | "reporting" | "ready";
  businessStatus: "complete" | "partial" | "insufficient";
  engine: EngineRef;
  isochrone: Record<string, unknown>;
  rules: DistanceRule;
  scope: ScopeEvidence;
  trace: TraceEvidence;
  facilities: FacilityGroup | null;
  facilitiesStatus: "not_integrated" | "complete" | "partial" | "failed";
  accessibility: AccessibilityEvidence | null;
  accessibilityStatus: "not_integrated" | "complete" | "partial" | "failed";
  serviceGaps: ServiceGapsEvidence | null;
  heatmap: HeatmapEvidence | null;
  scores: ScoreEvidence | null;
  verification: VerificationEvidence | null;
  report: ReportEvidence | null;
  water: WaterDataEvidence | null;
  warnings: Array<Issue>;
};

export type CheckupLayer = {
  layerId: string;
  revision: number;
  geometry: Record<string, unknown> | null;
  displayGeometry: Record<string, unknown> | null;
  document: Record<string, unknown> | null;
  resultHash: string;
};

export type FacilityRoute = {
  taskId: string;
  revision: number;
  facilityId: string;
  category: string;
  majorCategory: MajorCategory | null;
  origin: Origin;
  destination: Origin;
  straightLineM: number | null;
  withinRule: boolean | null;
  routeDistanceM: number | null;
  accessDistanceM: number | null;
  verificationLayer: "strict" | "endpoint_tolerance" | null;
  durationS: number | null;
  observedDurationS: number | null;
  poiStatus: "pending" | "verified_reachable" | "verified_unreachable";
  poiReason: string | null;
  evidenceGrade: "verified" | "model";
  routeOrigin: Origin | null;
  routeDestination: Origin | null;
  originOffsetM: number | null;
  destinationOffsetM: number | null;
  reason: string | null;
  provider: string;
  network: boolean;
  attempts: number;
  budget: Record<string, unknown>;
  notes: Array<string>;
};

export type CheckupCapabilities = {
  schemaVersion: string;
  engines: Array<Record<string, unknown>>;
  rules: Record<string, unknown>;
  dataVersions: Record<string, unknown>;
  coverage: Record<string, unknown>;
  budgets: Record<string, unknown>;
  poiPlanning: Record<string, unknown>;
  cache: Record<string, unknown>;
  facilityCategories: Record<string, unknown>;
  quota: Record<string, unknown>;
  waterReviews: Array<Record<string, unknown>>;
};

export type FacilityExtensionRequest = {
  schemaVersion?: "checkup-v1";
  clientRequestId: string;
  categories: Array<MajorCategory>;
  maxPoiRequests?: number | null;
};

export type FacilityExtensionView = {
  extensionId: string;
  taskId: string;
  baseRevision: number;
  clientRequestId: string;
  status: "queued" | "running" | "completed" | "partial" | "failed" | "cancelled";
  stage: "poi" | "ready" | null;
  categories: Array<MajorCategory>;
  budget: Record<string, unknown>;
  requests: number;
  networkRequests: number;
  facilitiesStatus: string | null;
  countsByCategory: Record<string, number>;
  stopReason: string | null;
  initialPlan: Record<string, unknown> | null;
  error: string | null;
  createdAt: number;
  finishedAt: number | null;
};

export type FacilityExtensionDocument = {
  extensionId: string;
  taskId: string;
  baseRevision: number;
  categories: Array<MajorCategory>;
  status: "completed" | "partial" | "failed" | "cancelled";
  facilitiesStatus: string | null;
  group: FacilityGroup | null;
  requests: number;
  networkRequests: number;
  budget: Record<string, unknown>;
  issues: Array<Issue>;
  notes: Array<string>;
};

export type FacilityRetryRequest = {
  schemaVersion?: "checkup-v1";
  clientRequestId: string;
  maxPoiRequests?: number | null;
};

export type FacilityRetryView = {
  retryId: string;
  taskId: string;
  baseRevision: number;
  clientRequestId: string;
  status: "queued" | "running" | "completed" | "partial" | "failed" | "cancelled";
  stage: "poi" | "ready" | null;
  budget: Record<string, unknown>;
  requests: number;
  networkRequests: number;
  facilitiesStatus: string | null;
  stopReason: string | null;
  initialPlan: Record<string, unknown> | null;
  error: string | null;
  createdAt: number;
  finishedAt: number | null;
};

export type SessionOpenRequest = {
  schemaVersion?: "checkup-v1";
  sessionId?: string | null;
  tabId?: string | null;
};

export type SessionView = {
  sessionId: string;
  tabId: string;
  leaseSeconds: number;
  expiresAt: number;
  resumed: boolean;
  openTabs: number;
  tasks: number;
};

export type RetainedCheckupView = {
  taskId: string;
  revision: number;
  stage: "isochrone" | "poi" | "accessibility" | "verification" | "reporting" | "ready";
  businessStatus: "complete" | "partial" | "insufficient";
  resultHash: string;
  summary: Record<string, unknown>;
  retention: RetentionView;
  notes: Array<string>;
};
